{
 "title": "App Overview",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Page Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "http_requests_main_total", "legendFormat": "Main Page" },
    { "expr": "http_requests_playlist_total", "legendFormat": "Playlist Page" },
    { "expr": "http_requests_track_total", "legendFormat": "Track Page" }
   ]
  },
  {
   "title": "Panel Requests Created Per 60s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_main_total[1m])",
     "legendFormat": "Main Page"
    },
    {
     "expr": "rate(http_requests_playlist_total[1m])",
     "legendFormat": "Playlist Page"
    },
    {
     "expr": "rate(http_requests_track_total[1m])",
     "legendFormat": "Track Page"
    }
   ]
  },
  {
   "title": "HTTP Requests Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "prometheus_http_requests_total", "legendFormat": "__auto" }
   ]
  }
 ]
}