name: CI for Flask Test Suite

on: push

jobs:
  test:
    runs-on: ubuntu-latest  # Let Docker choose based on the runner architecture

    container:
      image: python:3.12-buster  # Use the official Python image
      # No need to specify the platform; Docker will decide automatically

    services:
      rabbitmq:
        image: rabbitmq:3.9-management
        ports:
          - 5672:5672
        options: --health-cmd="rabbitmqctl status" --health-interval=10s --health-retries=3 --health-timeout=5s
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your app dependencies
          pip install coverage pytest  # Install coverage and pytest for testing

      - name: Run Flask tests with coverage
        run: |
          coverage run -m pytest app/tests/test_routes.py  # Path to your test file
          coverage report  # Print the coverage report to the CI logs
          coverage html    # Generate HTML report for viewing (optional)
      
      - name: Upload coverage results (optional)
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: htmlcov/  # Upload the HTML coverage report folder (if generated)
